Repository teddyliang/Meta-Mesh-Help-Desk, pull requests merged in 2023-04, with the labels that each got.

#62 [M2] Display multiple search results
  src/Pipfile
  src/Pipfile.lock
  src/SearchEngine/WebpageSearcher.py
  src/helpdesk_app/views.py
  src/helpdesk_proj/static/helpdesk_app/css/search.css
  src/templates/search.html
  src/tests/test_search.py
Labels: new-feature

#72 [M4] PR Display search results with alternating colors (#69)
  src/helpdesk_proj/static/helpdesk_app/css/search.css
  src/templates/search.html
Labels: new-feature

#76 [M4] Resource metrics
  src/helpdesk_app/migrations/0003_answerresource_clicks_answerresource_searches_and_more.py
  src/helpdesk_app/migrations/0004_rename_searches_answerresource_appearances.py
  src/helpdesk_app/models.py
  src/helpdesk_app/views.py
  src/helpdesk_proj/static/helpdesk_app/css/main.css
  src/helpdesk_proj/urls.py
  src/templates/resources.html
  src/templates/search.html
  src/tests/test_resource_stats.py
Labels: new-feature

#79 [M3] Frequently Asked Questions
  src/helpdesk_app/urls.py
  src/helpdesk_app/views.py
  src/helpdesk_proj/static/helpdesk_app/css/search.css
  src/locale/en/LC_MESSAGES/django.po
  src/locale/es/LC_MESSAGES/django.po
  src/templates/search.html
Labels: new-feature

#78 [M4] Make search page mobile friendly (fixes #16)
  src/helpdesk_proj/static/helpdesk_app/css/search.css
  src/templates/search.html
Labels: bug

#77 [M4] Added deployment guide and settings changes
  DEPLOYMENT.md
  images/instance.jpg
  images/securitygroup.jpg
  src/helpdesk_proj/settings.py
Labels: deployment

#93 [M5] Hide "accounts" from non-superusers and display superuser status
  src/templates/account.html
  src/templates/base.html
Labels: bug

#92 [M5] Fix footer bug (fixes #88)
  src/helpdesk_proj/static/helpdesk_app/css/search.css
Labels: bug

#90 [M5] Add user handbook & comprehensive documentation to README (fixes…
  README.md
Labels: documentation/process

#85 [M5] Added documentation on backing/restoring db and configuring the d…
  DEPLOYMENT.md
  images/add_dns_record.jpg
  src/helpdesk_proj/settings.py
Labels: documentation/process

#83 [M5] Autocomplete with category
  src/helpdesk_app/views.py
  src/helpdesk_proj/static/helpdesk_app/css/jquery-ui.css
  src/locale/en/LC_MESSAGES/django.po
  src/locale/es/LC_MESSAGES/django.po
  src/templates/search.html
  src/tests/test_autocomplete.py
Labels: new-feature

#94 [M5] moved search button on home page (fixes #80)
  src/helpdesk_proj/static/helpdesk_app/css/search.css
  src/locale/en/LC_MESSAGES/django.po
  src/locale/es/LC_MESSAGES/django.po
  src/templates/search.html
Labels: bug

#95 [M5] Search query edge cases handled (fixes #84)
  src/SearchEngine/WebpageSearcher.py
  src/tests/test_search.py
Labels: bug

#97 [M5] Change thumbs up to down (fixes #86)
  src/helpdesk_app/migrations/0005_rename_thumbsups_answerresource_thumbsdowns.py
  src/helpdesk_app/models.py
  src/helpdesk_app/views.py
  src/helpdesk_proj/urls.py
  src/locale/en/LC_MESSAGES/django.po
  src/locale/es/LC_MESSAGES/django.po
  src/templates/resources.html
  src/templates/search.html
  src/tests/test_resource_stats.py
Labels: new-feature
