Repository teddyliang/Meta-Mesh-Help-Desk, pull requests merged in 2023-03, with the labels that each got.

#33 [M2] Set up CI for Github repo (testing, linter)
  .github/workflows/main.yml
  src/requirements.txt
Labels: testing

#38 [M2] Added search engine key word functionality and ability to return a list
  .github/workflows/main.yml
  src/SearchEngine/SearchEngineManualTest.py
  src/SearchEngine/SearchEngineTest.py
  src/SearchEngine/WebpageSearcher.py
  src/helpdesk_app/views.py
Labels: new-feature

#54 [M2] Fixed Issues with the search engine test
  src/SearchEngine/SearchEngineTest.py
Labels: fixed-bug

#56 [M2] Implement resource and keyword support (#27, #28, #29, #51, #52)
  src/.flake8
  src/helpdesk_app/admin.py
  src/helpdesk_app/filters.py
  src/helpdesk_app/forms.py
  src/helpdesk_app/migrations/0002_answerresource_keyword.py
  src/helpdesk_app/migrations/0003_answerresource_updated_keyword_updated_and_more.py
  src/helpdesk_app/migrations/0004_answerresource_tags.py
  src/helpdesk_app/migrations/0005_alter_answerresource_tags.py
  src/helpdesk_app/migrations/0006_delete_keyword.py
  src/helpdesk_app/migrations/0007_alter_answerresource_tags.py
  src/helpdesk_app/models.py
  src/helpdesk_app/urls.py
  src/helpdesk_app/views.py
  src/helpdesk_proj/settings.py
  src/helpdesk_proj/static/helpdesk_app/css/main.css
  src/requirements.txt
  src/templates/base.html
  src/templates/resource_form.html
  src/templates/resources.html
  src/tests/test_keyword.py
  src/tests/test_resource.py
Labels: new-feature

#61 [M2] Link the search engine with the backend database
  .github/workflows/main.yml
  src/SearchEngine/SearchEngineTest.py
  src/SearchEngine/WebpageSearcher.py
  src/helpdesk_app/migrations/0001_initial.py
  src/helpdesk_app/migrations/0002_answerresource_keyword.py
  src/helpdesk_app/migrations/0003_answerresource_updated_keyword_updated_and_more.py
  src/helpdesk_app/migrations/0004_answerresource_tags.py
  src/helpdesk_app/migrations/0005_alter_answerresource_tags.py
  src/helpdesk_app/migrations/0006_delete_keyword.py
  src/helpdesk_app/migrations/0007_alter_answerresource_tags.py
  src/helpdesk_app/models.py
  src/helpdesk_app/views.py
  src/tests/test_search.py
Labels: new-feature, fixed-bug

#60 [M3] Migrate CI to Pipenv (#59)
  .github/workflows/main.yml
  README.md
  src/Pipfile
  src/Pipfile.lock
  src/requirements.txt
Labels: documentation/process
